// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'firebase_options.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart

/// // ...

/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvLkMMZB0BbcrTbILgccPfiYRq0FpDv_c',
    appId: '1:935820223612:web:bb360b9e4c42be0503d5f9',
    messagingSenderId: '935820223612',
    projectId: 'flight-follower',
    authDomain: 'flight-follower.firebaseapp.com',
    storageBucket: 'flight-follower.appspot.com',
    measurementId: 'G-95Z2DEM3G4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMadY-j9_sjN5ob4rqimwB91FXKxQPiXg',
    appId: '1:935820223612:android:27f0f8dde62c153803d5f9',
    messagingSenderId: '935820223612',
    projectId: 'flight-follower',
    storageBucket: 'flight-follower.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANcw3TqbNGTUQS3nXfhMZJT6rfnOXPiFw',
    appId: '1:935820223612:ios:4749aabc4d1dd50d03d5f9',
    messagingSenderId: '935820223612',
    projectId: 'flight-follower',
    storageBucket: 'flight-follower.appspot.com',
    iosClientId:
        '935820223612-qh4auo66vn4l27mkacqs7a0bed7a2cg4.apps.googleusercontent.com',
    iosBundleId: 'com.example.flightFollower',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANcw3TqbNGTUQS3nXfhMZJT6rfnOXPiFw',
    appId: '1:935820223612:ios:4749aabc4d1dd50d03d5f9',
    messagingSenderId: '935820223612',
    projectId: 'flight-follower',
    storageBucket: 'flight-follower.appspot.com',
    iosClientId:
        '935820223612-qh4auo66vn4l27mkacqs7a0bed7a2cg4.apps.googleusercontent.com',
    iosBundleId: 'com.example.flightFollower',
  );
}
