// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCs2KdP4KJwRxfK-bmMIxntSZlPHrB5alM',
    appId: '1:616646145851:web:87fdbdc91e08ec5f6e691e',
    messagingSenderId: '616646145851',
    projectId: 'flight-follower-dev',
    authDomain: 'flight-follower-dev.firebaseapp.com',
    storageBucket: 'flight-follower-dev.appspot.com',
    measurementId: 'G-C05P9WM6G3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqMtLojV6DmWciz7tZvitrID8agtA3oIw',
    appId: '1:616646145851:android:ce7445164df5a77e6e691e',
    messagingSenderId: '616646145851',
    projectId: 'flight-follower-dev',
    storageBucket: 'flight-follower-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoRrwImEN6QE27T1lXMxkVd-i5SSSCe2c',
    appId: '1:616646145851:ios:c690ce529fabdab16e691e',
    messagingSenderId: '616646145851',
    projectId: 'flight-follower-dev',
    storageBucket: 'flight-follower-dev.appspot.com',
    iosClientId: '616646145851-0vf3oom8k3v6q0b7b0ajdcibskbk69gq.apps.googleusercontent.com',
    iosBundleId: 'com.example.flightFollower',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoRrwImEN6QE27T1lXMxkVd-i5SSSCe2c',
    appId: '1:616646145851:ios:c690ce529fabdab16e691e',
    messagingSenderId: '616646145851',
    projectId: 'flight-follower-dev',
    storageBucket: 'flight-follower-dev.appspot.com',
    iosClientId: '616646145851-0vf3oom8k3v6q0b7b0ajdcibskbk69gq.apps.googleusercontent.com',
    iosBundleId: 'com.example.flightFollower',
  );
}
